{% set version = "2020.1.31" %}

package:
  name: imagecodecs-lite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imagecodecs/imagecodecs-{{ version }}.tar.gz
  sha256: 2e093bec9dc136818b9e9bf48231c142ee403fd9b6f6d2a5a8b9fbfd77002a3a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy 1.14.*
    - msinttypes  # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - imagecodecs_lite

about:
  home: https://www.lfd.uci.edu/~gohlke
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Subset of image transformation, compression, and decompression codecs"

extra:
  recipe-maintainers:
    - ocefpaf
