{% set version = "2020.1.31" %}

package:
  name: imagecodecs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imagecodecs/imagecodecs-{{ version }}.tar.gz
  sha256: 2e093bec9dc136818b9e9bf48231c142ee403fd9b6f6d2a5a8b9fbfd77002a3a

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.7.0,<3.8.0a0
    - pip
    - numpy 1.16.*
    - msinttypes  # [win]
    - blosc
    - brotli
    - bzip2
    - giflib
    - jpeg-turbo =1.5.* # for compat with WML CE 1.6.2
    - lcms2
    - libaec
    - libwebp
    - zstd
    - openjpeg =2.3.*
  run:
    - python >=3.7.0,<3.8.0a0
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('blosc') }}
    - {{ pin_compatible('brotli') }}
    - {{ pin_compatible('numpy') }}
    - jpeg-turbo =1.5.*

test:
  imports:
    - imagecodecs

about:
  home: https://www.lfd.uci.edu/~gohlke
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Subset of image transformation, compression, and decompression codecs"

extra:
  recipe-maintainers:
    - ocefpaf
